"use client";

import React from "react";
import { Quote, Sparkles, TrendingUp, AlertCircle } from "lucide-react";

export default function Reflection() {
  const wins = [
    "Successfully initialized Next.js 15 project skeleton and TailwindCSS config.",
    "Integrated the custom design system rules for 'expensive silence'.",
    "Protected a 3-hour evening deep focus session on setup tasks."
  ];

  const learnings = [
    "Dividing focus between styling and architecture setup simultaneously caused initial confusion. Better to build in clean linear phases.",
    "Setting up local fonts early prevents layout shifts and makes design evaluation much easier."
  ];

  return (
    <div className="min-h-screen w-full p-8 md:p-16 flex flex-col items-center bg-background">
      
      <div className="max-w-2xl w-full flex flex-col gap-12 mt-8">
        
        {/* Header Section */}
        <header className="flex flex-col gap-3">
          <span className="font-sans text-xs tracking-[0.25em] text-accent font-semibold uppercase">
            Growth Narrative
          </span>
          <h1 className="font-heading text-4xl md:text-5xl font-light text-foreground">
            Partner Reflection
          </h1>
          <p className="font-sans text-sm text-muted-foreground leading-relaxed">
            A reflective check-in generated by Zenkai, highlighting patterns and adjustments based on your recent work.
          </p>
        </header>

        {/* AI Reflection Quote Block */}
        <section className="bg-secondary/40 border border-border p-8 rounded-2xl relative flex flex-col gap-4">
          <div className="absolute top-6 right-6 text-accent/20">
            <Quote size={40} className="fill-accent/10" />
          </div>
          
          <span className="font-sans text-[10px] tracking-[0.2em] text-accent font-bold uppercase flex items-center gap-1.5">
            <Sparkles size={12} />
            Companion Insight
          </span>
          
          <p className="font-heading text-xl italic text-foreground leading-relaxed max-w-xl">
            "Achyut, you work best when focusing on one major objective at a time. Task switching reduced progress during the last three sessions. Let's protect your evening blocks today."
          </p>
          
          <div className="border-t border-border/60 pt-4 flex items-center gap-2 text-xs text-muted-foreground font-sans">
            <span>Generated on Friday, June 26, 2026</span>
          </div>
        </section>

        {/* Wins and Lessons Learned side-by-side */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          
          {/* Recent Wins */}
          <section className="space-y-4">
            <span className="font-sans text-[10px] tracking-[0.2em] text-accent/80 font-bold uppercase flex items-center gap-1.5">
              <TrendingUp size={12} className="text-accent" />
              Recent Wins
            </span>
            <div className="bg-card border border-border p-6 rounded-xl space-y-4">
              {wins.map((win, idx) => (
                <div key={idx} className="flex items-start gap-3">
                  <span className="h-1.5 w-1.5 rounded-full bg-accent mt-2 shrink-0" />
                  <p className="font-sans text-xs text-foreground leading-relaxed">{win}</p>
                </div>
              ))}
            </div>
          </section>

          {/* Lessons Learned */}
          <section className="space-y-4">
            <span className="font-sans text-[10px] tracking-[0.2em] text-accent/80 font-bold uppercase flex items-center gap-1.5">
              <AlertCircle size={12} className="text-accent" />
              Lessons Learned
            </span>
            <div className="bg-card border border-border p-6 rounded-xl space-y-4">
              {learnings.map((learning, idx) => (
                <div key={idx} className="flex items-start gap-3">
                  <span className="h-1.5 w-1.5 rounded-full bg-muted-foreground/40 mt-2 shrink-0" />
                  <p className="font-sans text-xs text-foreground leading-relaxed">{learning}</p>
                </div>
              ))}
            </div>
          </section>

        </div>

        {/* Behavior Changes / Growth Summary */}
        <section className="space-y-4">
          <span className="font-sans text-[10px] tracking-[0.2em] text-accent/80 font-bold uppercase block">
            Behavioral Shifts
          </span>
          <div className="bg-card border border-border p-6 rounded-xl">
            <div className="flex justify-between items-center mb-3">
              <span className="font-sans text-xs font-semibold text-foreground tracking-wide">
                Focus Consistency
              </span>
              <span className="font-sans text-xs text-accent font-semibold">+15% improvement</span>
            </div>
            <p className="font-sans text-xs text-muted-foreground leading-relaxed">
              Moving key design decisions to your evening blocks has improved focus completion by 15%. Cognitive load in the morning has decreased as planning is done the night before.
            </p>
          </div>
        </section>

      </div>

    </div>
  );
}
